# Generated by Django 3.2.6 on 2021-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
