# Generated by Django 3.2.6 on 2021-10-06 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211006_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='batch',
        ),
        migrations.AddField(
            model_name='assignments',
            name='sap',
            field=models.ForeignKey(default='00000000000', max_length=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sap'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sap',
            field=models.TextField(default='00000000000', max_length=11, null=True, unique=True),
        ),
    ]
