# Generated by Django 3.2.6 on 2021-10-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211006_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='sap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_name', models.TextField(default='BRANCH', unique=True)),
                ('branch_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('sap', models.ForeignKey(default='00000000000', max_length=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sap')),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='branch_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch'),
        ),
    ]
