# Generated by Django 3.2.6 on 2021-10-07 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211006_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_name', models.TextField(default='Announcement', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignments',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.TextField(default='NAME', null=True)),
                ('faculty_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('faculty_email', models.EmailField(default='test@gmail.com', max_length=255, unique=True, verbose_name='email address')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
            ],
        ),
    ]
