# Generated by Django 3.2.8 on 2021-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211007_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcement'},
        ),
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branch'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
