# Generated by Django 3.2.8 on 2021-10-24 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211024_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('m2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('termwork', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('total', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='PASS', max_length=10)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
            ],
            options={
                'verbose_name_plural': 'ICA',
            },
        ),
    ]
