# Generated by Django 3.2.7 on 2021-10-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20211026_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sap',
            field=models.ForeignKey(default='00000000000', max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='sap'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sap',
            field=models.ForeignKey(default='00000000000', max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='sap'),
        ),
        migrations.AlterField(
            model_name='ica',
            name='sap',
            field=models.ForeignKey(default='00000000000', max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='sap'),
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
